---

- name: Install xorg, xmonad and related
  pkgng: name=xorg,slim,hs-xmonad,hs-xmonad-contrib,tint2,conky,dmenu,clipit,xclip state=present
  become: yes

- name: Install other desktop utils
  pkgng: name=konsole,nitrogen,lxrandr,en-hunspell,nathive,password-store,htop state=present
  become: yes

- name: Install clementine
  pkgng: name=clementine-player state=present
  become: yes

- name: Install chat/web progs
  pkgng: name=chromium,firefox,pidgin,weechat,mumble state=present
  become: yes

- name: Install calibre
  pkgng: name=calibre state=present
  become: yes

- name: Install fonts
  pkgng: name=urwfonts
  become: yes

- name: enable hald
  lineinfile: dest=/etc/rc.conf line="hald_enable=\"YES\"" state=present
  become: yes

- name: enable dbus
  lineinfile: dest=/etc/rc.conf line="dbus_enable=\"YES\"" state=present
  become: yes

- name: enable slim
  lineinfile: dest=/etc/rc.conf line="slim_enable=\"YES\"" state=present
  become: yes

- name: enable fdesc in fstab
  lineinfile: dest=/etc/fstab line="fdesc /dev/fd fdescfs rw 0 0" state=present
  become: yes
