(source org)
(source melpa)
(source gnu)

(files :defaults "*.el" "proglang/*.el")

(depends-on "bind-key")
(depends-on "cask")
(depends-on "exec-path-from-shell")
(depends-on "flycheck-cask")
(depends-on "magit")
(depends-on "use-package")

;; be more helpful
(depends-on "helpful")
(depends-on "command-log-mode")

;; theming and display stuff
(depends-on "color-theme-modern")
(depends-on "darkokai-theme")
(depends-on "diminish") ;; hide modes from modeline
(depends-on "fic-mode")  ;; show fixme/todo with special faces

(depends-on "persp-mode")

(depends-on "sr-speedbar")
(depends-on "flycheck") ;; on the fly checking

;; rainbow modes
(depends-on "rainbow-delimiters")
(depends-on "rainbow-identifiers")
(depends-on "rainbow-mode")

;; ido mode
(depends-on "ido-vertical-mode")
(depends-on "ido-completing-read+")

;; company mode
(depends-on "company") ;; autocompletion support
(depends-on "company-dict")
(depends-on "company-quickhelp")
(depends-on "company-shell")
(depends-on "company-statistics")

;; file movement (undo, expand, jump words, etc)
(depends-on "expand-region")
(depends-on "paredit") ;; make sure paredit gets installed
(depends-on "paredit-menu")
(depends-on "smartparens") ;; smart parens are better than not smart parens
(depends-on "syntax-subword") ;; make movement more fine-grained
(depends-on "undo-tree") ;; traverse a tree for undo/redo

;; buffer/window movement
(depends-on "buffer-move")
(depends-on "window-jump")

;; keybindings
(depends-on "which-key")

;; helm and smex
(depends-on "helm")
(depends-on "smex")

;; searching stuff
(depends-on "ag") ;; ag support
(depends-on "projectile") ;; per project support

;; terminal/shells
(depends-on "tramp") ;; edit remote files
(depends-on "multi-term")
(depends-on "multishell")

;; csv
(depends-on "csv-mode")

;; C/C++ and related
(depends-on "ac-clang") ;; autocomplete via clang
(depends-on "clang-format") ;; support the clang-format tool
(depends-on "cmake-font-lock")
(depends-on "cmake-mode")
(depends-on "cmake-project")
(depends-on "cmake-ide")
(depends-on "company-c-headers")
(depends-on "company-irony-c-headers")
(depends-on "company-irony") ;; autocomplete via libclang
(depends-on "cpputils-cmake")
(depends-on "flycheck-clang-analyzer") ;; enable clang static-analysis
(depends-on "flycheck-clang-tidy")
(depends-on "flycheck-irony")
(depends-on "irony") ;; c/c++ minor mode via libclang
(depends-on "modern-cpp-font-lock")

;; Dhall configuration language
(depends-on "dhall-mode")

;; Haskell
(depends-on "ac-haskell-process") ;; autocomplete via a haskell process
(depends-on "company-ghci")
(depends-on "company-ghc")
(depends-on "flycheck-haskell") ;; flycheck support
(depends-on "hasky-stack")
(depends-on "ghc")
(depends-on "hlint-refactor") ;; refactoring via hlint
;(depends-on "stack-mode") ;; stack integration
;(depends-on "lsp-mode") ;; language server protocol
;(depends-on "lsp-ui")
;(depends-on "lsp-haskell")
;(depends-on "lsp-flycheck")
;(depends-on "company-lsp")

; ;; Javascript... because the world is sad...
(depends-on "ac-js2")
(depends-on "flymake-jshint")
(depends-on "flymake-jslint")
(depends-on "flymake-json")
(depends-on "js2-highlight-vars")
(depends-on "js2-mode")
(depends-on "js2-refactor")
(depends-on "js-format")
(depends-on "npm-mode")
(depends-on "prettier-js")

;; Lua
(depends-on "company-lua") ;; autocomplete lua
(depends-on "flymake-lua") ;; autobuild lua
(depends-on "lua-mode") ;; lua
(depends-on "luarocks")


; ;; Ruby
(depends-on "company-inf-ruby") ;; company ruby
(depends-on "robe")
(depends-on "rspec-mode") ;; support rspecs
(depends-on "rubocop") ;; run rubocop in editior
(depends-on "ruby-mode")
(depends-on "ruby-tools") ;; extra ruby tooling
(depends-on "yari")

;; Web/html/stuff
(depends-on "company-web")
(depends-on "web-beautify")
(depends-on "web-mode")

;;; Other kinds of files that aren't exactly programming languages

;; Dockerfile, docker-compose
(depends-on "docker-compose-mode")
(depends-on "dockerfile-mode")
(depends-on "docker-tramp")

;; Orgmode
(depends-on "calfw")
(depends-on "calfw-ical")
(depends-on "calfw-org")
(depends-on "ivy-todo")
(depends-on "org")
(depends-on "org-ac") ;; autocomplete
(depends-on "org-caldav")
(depends-on "org-cliplink")
(depends-on "org-ref")
(depends-on "org-projectile")
(depends-on "org-review")
(depends-on "org-vcard") ;; vcard support
(depends-on "org-wc")
(depends-on "toc-org") ;; table of contents

;; perspectives
(depends-on "perspective")

;; chat stuff
; (depends-on "znc")
