---

- name: Install cabal
  pkgng: name=hs-cabal-install state=present
  become: yes

- name: Install stack
  command: cabal install stack

- name: Run stack setup
  command: stack setup

- name: Install haskell progs with stack
  command: stack install alex happy stylish-haskell hindent dash-haskell hasktags
